---
title: "Getting and Cleaning Data WK4 Assignment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose this Codebook
This Codebook describes the variables, the data, and any transformations or work completed to clean up the data.

## Source of Data
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

## Variables of run_analysis.R
1. activity_labels: reading of all activities and their names and label the appropriate columns
2. features: read dataframe column names
3. testdata: read test data and label dataframe columns
4. traindata: read training data and label dataframe columns
5. test_subject_id: read ids of test subjects and label dataframe columns
6. test_activity_id: read activity id of test data and label dataframe columns
7. train_subject_id: read ids of test subjects and label dataframe columns
8. train_activity_id: read activity id of training data and lable dataframe columns
9. test_data: combine test subject id, the test activity id and the test data into one dataframe
10. train_data: combine test subject id, the test activity id and the test data into one dataframe
11. all_data: combine test data and train data into one dataframe
12. mean_col_idx, mean_col_names: mean values to be kept
13. std_col_idx, std_col_names: std values to be kept
14. descrnames, data_melt: merger of activity dataset with mean/std values dataset and give descriptvie activity names

